controller_list:
<<<<<<< HEAD
  - name: "joint_trajectory_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
  - name: ""
    action_ns: joint_trajectory_action
=======
  - name: /joint_trajectory_controller
    action_ns: follow_joint_trajectory
>>>>>>> a1d9874fefe72b122c0dea4922a76058cf184b9e
    type: FollowJointTrajectory
    default: true
    joints: 
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6

